ALTER TABLE package_master
ADD COLUMN category VARCHAR(255) NULL,
ADD COLUMN price DECIMAL(10,2) NULL,
ADD COLUMN original_price DECIMAL(10,2) NULL,
ADD COLUMN description TEXT NULL,
ADD COLUMN image_url VARCHAR(255) NULL,
ADD COLUMN min_guests INT NULL,
ADD COLUMN max_guests INT NULL,
ADD COLUMN status VARCHAR(255) NULL,
ADD COLUMN tags VARCHAR(255) NULL;

ALTER TABLE ingredient_master
ADD COLUMN category VARCHAR(255) NULL,
ADD COLUMN unit VARCHAR(255) NULL,
ADD COLUMN min_stock DECIMAL(10,3) NULL,
ADD COLUMN unit_price DECIMAL(10,2) NULL,
ADD COLUMN supplier_id INT NULL,
ADD COLUMN status VARCHAR(255) NULL;

ALTER TABLE supplier_master
ADD COLUMN phone VARCHAR(255) NULL,
ADD COLUMN email VARCHAR(255) NULL,
ADD COLUMN address TEXT NULL,
ADD COLUMN category VARCHAR(255) NULL,
ADD COLUMN payment_terms VARCHAR(255) NULL,
ADD COLUMN status VARCHAR(255) NULL,
ADD COLUMN notes TEXT NULL;

ALTER TABLE dish_recipe
ADD COLUMN notes TEXT NULL;

ALTER TABLE ingredient_purchase
ADD COLUMN quantity DECIMAL(10,3) NULL,
ADD COLUMN unit_price DECIMAL(10,2) NULL,
ADD COLUMN total_amount DECIMAL(12,2) NULL,
ADD COLUMN approved_by VARCHAR(255) NULL,
ADD COLUMN approved_at DATETIME NULL,
ADD COLUMN notes TEXT NULL,
ADD COLUMN updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
