FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'Wo002323';
CREATE USER IF NOT EXISTS 'rino'@'localhost' IDENTIFIED BY 'Wo002323';
GRANT ALL PRIVILEGES ON banquet.* TO 'rino'@'localhost';
FLUSH PRIVILEGES;
