-- Production restaurant structure captured 2026-09-06. No production data.
-- Two external parent stubs only provide empty identity targets; no staff/auth/legal content.
CREATE TABLE staff_master (staff_id INT PRIMARY KEY);
CREATE TABLE dish_category (id INT PRIMARY KEY);

CREATE TABLE `store_info` (
  `store_id` bigint NOT NULL AUTO_INCREMENT COMMENT '门店ID',
  `store_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '门店编码',
  `store_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '门店名称',
  `store_short_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `store_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'normal' COMMENT '类型',
  `store_level` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '等级',
  `address` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '地址',
  `latitude` decimal(10,6) DEFAULT NULL,
  `longitude` decimal(10,6) DEFAULT NULL,
  `province` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '省',
  `city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '市',
  `district` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '区',
  `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '手机号',
  `contact_person` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '联系人',
  `business_hours` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '营业时间',
  `table_count` int DEFAULT '0' COMMENT '数量',
  `max_capacity` int DEFAULT '0' COMMENT '最大容量',
  `business_area` decimal(8,2) DEFAULT NULL COMMENT '营业面积',
  `manager_id` int DEFAULT NULL COMMENT '店长ID',
  `manager_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `opening_date` date DEFAULT NULL COMMENT '日期',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'open' COMMENT '状态',
  `tax_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '个税',
  `bank_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `bank_account` varchar(255) DEFAULT NULL,
  `logo_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'URL',
  `store_image_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '图片URL',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`store_id`),
  UNIQUE KEY `uk_store_code` (`store_code`),
  KEY `idx_status` (`status`),
  KEY `fk_store_info_manager_id` (`manager_id`),
  CONSTRAINT `fk_store_info_manager_id` FOREIGN KEY (`manager_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='门店信息表';

CREATE TABLE `supplier_master` (
  `supplier_id` int NOT NULL AUTO_INCREMENT,
  `store_id` bigint NOT NULL DEFAULT '1',
  `supplier_code` varchar(20) DEFAULT NULL,
  `supplier_name` varchar(100) NOT NULL,
  `contact_person` varchar(50) DEFAULT NULL,
  `contact_phone` varchar(20) DEFAULT NULL,
  `bank_account` varchar(255) DEFAULT NULL,
  `platform_account` varchar(100) DEFAULT NULL,
  `main_products` text,
  `wechat_account` varchar(50) DEFAULT NULL,
  `alipay_account` varchar(50) DEFAULT NULL,
  `taobao_account` varchar(50) DEFAULT NULL,
  `supplier_rating` int DEFAULT '5',
  `is_active` tinyint DEFAULT '1',
  `remark` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `phone` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `address` text,
  `category` varchar(255) DEFAULT NULL,
  `payment_terms` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`supplier_id`),
  KEY `idx_store` (`store_id`),
  KEY `idx_name` (`supplier_name`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ingredient_master` (
  `ingredient_id` varchar(50) NOT NULL COMMENT '原料编号',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID(1宁国/2宣城)',
  `ingredient_name` varchar(100) NOT NULL COMMENT '原料名称',
  `ingredient_category` varchar(50) DEFAULT NULL COMMENT '原料分类(原始分类,已弃用,用category)',
  `brand` varchar(100) DEFAULT NULL COMMENT '品牌',
  `spec` varchar(100) DEFAULT NULL COMMENT '规格(如1x12x750ml)',
  `purchase_unit` varchar(20) DEFAULT NULL COMMENT '采购单位',
  `usage_unit` varchar(20) DEFAULT NULL COMMENT '使用单位',
  `conversion_rate` decimal(10,3) DEFAULT NULL COMMENT '采购单位到使用单位换算倍率',
  `primary_supplier_id` int DEFAULT NULL COMMENT '首选供应商ID(已弃用,用supplier_id)',
  `current_stock` decimal(12,3) DEFAULT NULL COMMENT '当前库存(使用单位)',
  `warning_threshold` decimal(10,3) DEFAULT NULL COMMENT '库存预警阈值(已弃用,用min_stock)',
  `avg_price` decimal(10,4) DEFAULT NULL COMMENT '加权平均单价(已弃用,用unit_price)',
  `yield_rate` decimal(5,2) DEFAULT NULL COMMENT '出成率(%)',
  `last_entry_date` date DEFAULT NULL COMMENT '最近入库日期',
  `is_active` tinyint DEFAULT NULL COMMENT '是否启用(已弃用,用status)',
  `sort_order` int DEFAULT NULL COMMENT '排序序号',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `category` varchar(255) DEFAULT NULL COMMENT '原料分类(水产/畜肉/蔬菜/调味/粮油/禽蛋/其他)',
  `unit` varchar(255) DEFAULT NULL COMMENT '计量单位(斤/只/袋/箱/条/盘/桶)',
  `min_stock` decimal(10,3) DEFAULT NULL COMMENT '最低库存预警值',
  `unit_price` decimal(15,8) DEFAULT NULL COMMENT '采购单价(元)',
  `supplier_id` int DEFAULT NULL COMMENT '供应商ID',
  `status` varchar(255) DEFAULT NULL COMMENT '状态(active/inactive)',
  PRIMARY KEY (`ingredient_id`,`store_id`),
  UNIQUE KEY `idx_ingredient_id` (`ingredient_id`),
  KEY `idx_store` (`store_id`),
  KEY `idx_category` (`ingredient_category`),
  KEY `idx_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `purchase_order` (
  `order_id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `order_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单编号',
  `supplier_id` int DEFAULT NULL COMMENT '供应商ID',
  `supplier_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '供应商名称',
  `order_date` date NOT NULL COMMENT '订单日期',
  `expected_date` date DEFAULT NULL COMMENT '日期',
  `total_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '合计',
  `total_amount` decimal(12,2) DEFAULT '0.00' COMMENT '合计',
  `received_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '数量',
  `received_amount` decimal(12,2) DEFAULT '0.00' COMMENT '金额',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'pending' COMMENT '状态',
  `order_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'normal' COMMENT '类型',
  `purchaser_id` int DEFAULT NULL COMMENT '采购员ID',
  `purchaser_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `approver_id` int DEFAULT NULL COMMENT '审批人ID',
  `approver_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `approve_time` datetime DEFAULT NULL COMMENT '时间',
  `warehouse_keeper_id` int DEFAULT NULL COMMENT '库管员ID',
  `warehouse_keeper_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `idx_order_no` (`order_no`),
  KEY `idx_order_date` (`order_date`),
  KEY `idx_status` (`status`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_supplier_id` (`supplier_id`),
  KEY `fk_purchase_order_purchaser_id` (`purchaser_id`),
  KEY `fk_purchase_order_approver_id` (`approver_id`),
  KEY `fk_purchase_order_warehouse_keeper_id` (`warehouse_keeper_id`),
  CONSTRAINT `fk_purchase_order_approver_id` FOREIGN KEY (`approver_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_order_purchaser_id` FOREIGN KEY (`purchaser_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_order_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `supplier_master` (`supplier_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_order_warehouse_keeper_id` FOREIGN KEY (`warehouse_keeper_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购订单表(申请→审批→下达, 记录采购主信息)';

CREATE TABLE `purchase_receipt` (
  `receipt_id` bigint NOT NULL AUTO_INCREMENT COMMENT '收货单ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `receipt_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '收货单号',
  `receipt_date` date NOT NULL COMMENT '日期',
  `order_id` bigint DEFAULT NULL COMMENT '订单ID',
  `order_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '订单编号',
  `supplier_id` int DEFAULT NULL COMMENT '供应商ID',
  `supplier_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '供应商名称',
  `total_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '合计',
  `total_amount` decimal(12,2) DEFAULT '0.00' COMMENT '合计',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'confirmed' COMMENT '状态',
  `warehouse_keeper_id` int DEFAULT NULL COMMENT '库管员ID',
  `warehouse_keeper_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `delivery_person` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '配送人',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`receipt_id`),
  UNIQUE KEY `idx_receipt_no` (`receipt_no`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_receipt_date` (`receipt_date`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_supplier_id` (`supplier_id`),
  KEY `fk_purchase_receipt_warehouse_keeper_id` (`warehouse_keeper_id`),
  CONSTRAINT `fk_purchase_receipt_order_id` FOREIGN KEY (`order_id`) REFERENCES `purchase_order` (`order_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_receipt_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `supplier_master` (`supplier_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_receipt_warehouse_keeper_id` FOREIGN KEY (`warehouse_keeper_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购收货表(验收+入库, 记录到货验收主信息)';

CREATE TABLE `purchase_receipt_detail` (
  `detail_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `receipt_id` bigint NOT NULL COMMENT '收货单ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `line_no` int NOT NULL COMMENT 'line编号',
  `order_detail_id` bigint DEFAULT NULL COMMENT '订单明细ID',
  `ingredient_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'NULL' COMMENT '食材ID',
  `ingredient_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '原料名称',
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '分类',
  `spec` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '规格',
  `unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '单位',
  `order_quantity` decimal(10,2) DEFAULT NULL COMMENT '数量',
  `actual_quantity` decimal(10,2) NOT NULL COMMENT '数量',
  `unit_price` decimal(15,8) DEFAULT NULL,
  `amount` decimal(15,4) DEFAULT NULL,
  `quality_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'qualified' COMMENT '状态',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`detail_id`),
  KEY `idx_ingredient_id` (`ingredient_id`),
  KEY `idx_receipt_id` (`receipt_id`),
  KEY `idx_store_id` (`store_id`),
  KEY `fk_purchase_receipt_detail_ingredient_id` (`ingredient_id`,`store_id`),
  CONSTRAINT `fk_purchase_receipt_detail_ingredient_id` FOREIGN KEY (`ingredient_id`, `store_id`) REFERENCES `ingredient_master` (`ingredient_id`, `store_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_purchase_receipt_detail_receipt_id` FOREIGN KEY (`receipt_id`) REFERENCES `purchase_receipt` (`receipt_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购收货明细表(每批到货的原料验收明细行)';

CREATE TABLE `ingredient_inventory_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '流水ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `food_material_id` varchar(50) NOT NULL COMMENT '原料编码(FK→food_material_master)',
  `change_type` varchar(20) NOT NULL COMMENT '变动类型(入库IN/领用OUT/报损LOSS/加工损耗YIELD/调拨TRANSFER/盘点ADJUST)',
  `change_quantity` decimal(12,3) NOT NULL COMMENT '变动数量(正数入库,负数出库)',
  `change_direction` varchar(10) NOT NULL COMMENT '方向(IN增加/OUT减少)',
  `source_type` varchar(20) DEFAULT NULL COMMENT '来源类型(PURCHASE采购入库/REQUISITION领用/LOSS报损/YIELD出成加工)',
  `source_id` varchar(50) DEFAULT NULL COMMENT '来源单据ID(关联采购单/领用单/报损单)',
  `before_quantity` decimal(12,3) DEFAULT NULL COMMENT '变动前库存',
  `after_quantity` decimal(12,3) DEFAULT NULL COMMENT '变动后库存',
  `unit_price` decimal(12,6) DEFAULT NULL COMMENT '变动时成本单价',
  `total_amount` decimal(12,2) DEFAULT NULL COMMENT '变动总金额',
  `operator_id` int DEFAULT NULL COMMENT '操作人ID(FK→staff_master)',
  `operate_time` datetime NOT NULL COMMENT '操作时间',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `is_deleted` tinyint DEFAULT '0' COMMENT '逻辑删除',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`log_id`),
  KEY `idx_log_store` (`store_id`),
  KEY `idx_log_material` (`food_material_id`),
  KEY `idx_log_type` (`change_type`),
  KEY `idx_log_time` (`operate_time`),
  KEY `idx_log_source` (`source_id`),
  KEY `fk_log_operator` (`operator_id`),
  CONSTRAINT `fk_iil_material` FOREIGN KEY (`food_material_id`) REFERENCES `ingredient_master` (`ingredient_id`),
  CONSTRAINT `fk_log_operator` FOREIGN KEY (`operator_id`) REFERENCES `staff_master` (`staff_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存流水表(入库+/领用-/报损-/加工损耗-,全变动留痕)';

CREATE TABLE `material_requisition` (
  `requisition_id` bigint NOT NULL AUTO_INCREMENT,
  `store_id` bigint NOT NULL DEFAULT '1',
  `department_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `requisition_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'PENDING',
  `requested_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `approved_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `requisition_date` date DEFAULT NULL,
  `total_amount` decimal(12,2) DEFAULT NULL,
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`requisition_id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `material_requisition_item` (
  `item_id` bigint NOT NULL AUTO_INCREMENT,
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID(冗余,便于按门店隔离)',
  `requisition_id` bigint NOT NULL,
  `ingredient_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ingredient_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `quantity` decimal(10,3) DEFAULT NULL,
  `unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `unit_price` decimal(10,2) DEFAULT NULL,
  `amount` decimal(12,2) DEFAULT NULL,
  `notes` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  KEY `idx_requisition_id` (`requisition_id`),
  KEY `idx_mri_store` (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `preprocessing_record` (
  `record_id` bigint NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `store_id` bigint DEFAULT NULL COMMENT '门店ID(多租户隔离)',
  `ingredient_id` varchar(50) DEFAULT NULL COMMENT '食材ID',
  `ingredient_name` varchar(100) DEFAULT NULL COMMENT '食材名称',
  `raw_qty` decimal(10,3) DEFAULT NULL COMMENT '原料数量',
  `processed_qty` decimal(10,3) DEFAULT NULL COMMENT '加工后数量',
  `yield_rate` decimal(5,2) DEFAULT NULL COMMENT '出成率(%)',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `preprocessing_type` varchar(50) DEFAULT NULL COMMENT '预处理类型(清洗/切配/腌制等)',
  `record_date` date DEFAULT NULL COMMENT '记录日期',
  `operator` varchar(50) DEFAULT NULL COMMENT '操作人',
  `notes` text COMMENT '备注说明',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`record_id`),
  KEY `idx_store_preprocess` (`store_id`),
  KEY `idx_ingredient_preprocess` (`ingredient_id`),
  KEY `idx_date_preprocess` (`record_date`),
  CONSTRAINT `fk_preprocess_store` FOREIGN KEY (`store_id`) REFERENCES `store_info` (`store_id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='预处理记录表';

CREATE TABLE `dish_master` (
  `dish_id` varchar(20) NOT NULL COMMENT '菜品ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `dish_name` varchar(100) NOT NULL COMMENT '菜品名称',
  `dish_category` varchar(50) DEFAULT NULL COMMENT '菜品分类',
  `spicy_level` int DEFAULT '0' COMMENT '辣度',
  `main_ingredient_type` varchar(50) DEFAULT NULL COMMENT '主料类型',
  `main_ingredient` varchar(100) DEFAULT NULL COMMENT '主料',
  `english_name` varchar(200) DEFAULT NULL COMMENT '英文名',
  `cost_price` decimal(10,2) DEFAULT '0.00' COMMENT '成本价',
  `sale_price` decimal(10,2) DEFAULT '0.00' COMMENT '售价',
  `cost_rate` decimal(5,2) DEFAULT '0.00' COMMENT '成本率',
  `cooking_time` int DEFAULT '15' COMMENT '烹饪时间',
  `servings` int DEFAULT '1' COMMENT '份数',
  `birthday_name` varchar(100) DEFAULT NULL COMMENT '生日菜品名',
  `wedding_name` varchar(100) DEFAULT NULL COMMENT '婚宴菜品名',
  `house_move_name` varchar(100) DEFAULT NULL COMMENT '乔迁菜品名',
  `promotion_name` varchar(100) DEFAULT NULL COMMENT '促销菜品名',
  `reunion_name` varchar(100) DEFAULT NULL COMMENT '团圆菜品名',
  `thanksgiving_name` varchar(100) DEFAULT NULL COMMENT '感恩节菜品名',
  `year_end_name` varchar(100) DEFAULT NULL COMMENT '年终菜品名',
  `baby_born_name` varchar(100) DEFAULT NULL COMMENT '满月菜品名',
  `business_name` varchar(100) DEFAULT NULL COMMENT '商务宴菜名',
  `spring_name` varchar(100) DEFAULT NULL COMMENT '新春宴菜名',
  `school_name` varchar(100) DEFAULT NULL COMMENT '升学宴菜名',
  `victory_name` varchar(100) DEFAULT NULL COMMENT '凯旋宴菜名',
  `opening_name` varchar(100) DEFAULT NULL COMMENT '开业宴菜名',
  `comrade_name` varchar(100) DEFAULT NULL COMMENT '战友聚会菜名',
  `teacher_name` varchar(100) DEFAULT NULL COMMENT '谢师宴菜名',
  `adult_name` varchar(100) DEFAULT NULL COMMENT '成人礼宴菜名',
  `is_active` tinyint DEFAULT '1' COMMENT '是否启用',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `usage_type` varchar(20) DEFAULT 'unused' COMMENT '用途类型',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `image_url` varchar(500) DEFAULT NULL COMMENT '图片URL',
  `dish_intro` text COMMENT '菜品介绍',
  `tiktok_recommend` text COMMENT '抖音推荐语',
  `festive_name` varchar(100) DEFAULT NULL COMMENT '节日名称',
  `menu_type` varchar(20) DEFAULT 'alacarte' COMMENT '菜单类型',
  `category` varchar(50) DEFAULT NULL COMMENT '分类',
  `category_id` int DEFAULT NULL COMMENT '分类ID',
  `cooking_method` varchar(50) DEFAULT NULL COMMENT '烹饪方法',
  `dish_code` varchar(64) DEFAULT NULL COMMENT '菜品编码',
  `dish_name_en` varchar(100) DEFAULT NULL COMMENT '菜品英文名',
  `is_seasonal` int DEFAULT '0' COMMENT '是否时令',
  `is_specialty` int DEFAULT '0' COMMENT '是否招牌',
  `main_ingredients` text COMMENT '主料列表',
  `taste` varchar(50) DEFAULT NULL COMMENT '口味',
  `unit` varchar(32) DEFAULT '?' COMMENT '单位',
  `remark` text COMMENT '备注',
  PRIMARY KEY (`dish_id`,`store_id`),
  UNIQUE KEY `uk_dish_id` (`dish_id`),
  KEY `idx_store` (`store_id`),
  KEY `idx_category` (`dish_category`),
  KEY `idx_active` (`is_active`),
  KEY `fk_dish_master_category_id` (`category_id`),
  CONSTRAINT `fk_dish_master_category_id` FOREIGN KEY (`category_id`) REFERENCES `dish_category` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜肴主表(成本率校验通过后入库的菜肴档案, 含售价/成本/成本率)';

CREATE TABLE `dish_recipe` (
  `recipe_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `dish_id` varchar(20) NOT NULL COMMENT '菜品ID',
  `ingredient_id` varchar(50) NOT NULL COMMENT '原料ID',
  `ingredient_name` varchar(100) DEFAULT NULL COMMENT '原料名称',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `unit_price` decimal(15,8) DEFAULT NULL,
  `quantity` decimal(10,3) DEFAULT '0.000' COMMENT '数量',
  `total_cost` decimal(15,4) DEFAULT NULL,
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `wastage_rate` decimal(5,2) DEFAULT '0.00' COMMENT '损耗率',
  `yield_rate` decimal(5,2) DEFAULT '0.00' COMMENT '产出率',
  `last_entry_date` date DEFAULT NULL COMMENT '入职日期',
  `net_unit_price` decimal(15,8) DEFAULT NULL,
  `notes` text COMMENT '备注',
  PRIMARY KEY (`recipe_id`),
  KEY `idx_store` (`store_id`),
  KEY `idx_dish` (`dish_id`),
  KEY `idx_ingredient` (`ingredient_id`),
  KEY `fk_dish_recipe_ingredient_id` (`ingredient_id`,`store_id`),
  CONSTRAINT `fk_dish_recipe_dish_id` FOREIGN KEY (`dish_id`) REFERENCES `dish_master` (`dish_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_dish_recipe_ingredient_id` FOREIGN KEY (`ingredient_id`, `store_id`) REFERENCES `ingredient_master` (`ingredient_id`, `store_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜品配方表';

CREATE TABLE `dish_cost_card` (
  `cost_card_id` bigint NOT NULL AUTO_INCREMENT COMMENT '成本卡ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `dish_id` varchar(50) NOT NULL COMMENT '菜品ID',
  `dish_name` varchar(100) NOT NULL COMMENT '菜品名称',
  `dish_category` varchar(50) DEFAULT NULL COMMENT '菜品分类',
  `standard_yield` decimal(10,3) DEFAULT NULL COMMENT '标准产出率',
  `actual_yield` decimal(10,3) DEFAULT NULL COMMENT '实际产出率',
  `yield_rate` decimal(5,2) DEFAULT NULL COMMENT '产出率',
  `standard_cost` decimal(15,4) DEFAULT NULL,
  `actual_cost` decimal(15,4) DEFAULT NULL,
  `selling_price` decimal(12,2) DEFAULT NULL COMMENT '价格',
  `gross_margin` decimal(5,2) DEFAULT NULL COMMENT '毛利率',
  `status` varchar(20) DEFAULT 'active' COMMENT '状态',
  `effective_date` datetime DEFAULT NULL COMMENT '日期',
  `created_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`cost_card_id`),
  KEY `idx_store_costcard` (`store_id`),
  KEY `idx_dish_costcard` (`dish_id`),
  KEY `idx_status_costcard` (`status`),
  CONSTRAINT `fk_dish_cost_card_dish_id` FOREIGN KEY (`dish_id`) REFERENCES `dish_master` (`dish_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='菜品成本卡表';
