-- Historical schema snapshot. Compare with current SHOW CREATE before release.
CREATE TABLE `stock_take` (
  `take_id` bigint NOT NULL AUTO_INCREMENT,
  `store_id` bigint NOT NULL DEFAULT '1',
  `take_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `take_date` date NOT NULL,
  `take_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'full',
  `category_id` int DEFAULT NULL,
  `warehouse_id` int DEFAULT NULL,
  `total_items` int DEFAULT '0',
  `total_diff_items` int DEFAULT '0',
  `total_diff_amount` decimal(12,2) DEFAULT '0.00',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  `operator_id` int DEFAULT NULL,
  `operator_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supervisor_id` int DEFAULT NULL,
  `supervisor_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `finish_time` datetime DEFAULT NULL,
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`take_id`),
  UNIQUE KEY `idx_take_no` (`take_no`),
  KEY `idx_status` (`status`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_take_date` (`take_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盘点单主档表';

CREATE TABLE `stock_take_detail` (
  `detail_id` bigint NOT NULL AUTO_INCREMENT,
  `take_id` bigint NOT NULL,
  `store_id` bigint NOT NULL DEFAULT '1',
  `line_no` int NOT NULL,
  `ingredient_id` int DEFAULT NULL,
  `ingredient_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `system_quantity` decimal(10,2) NOT NULL,
  `system_amount` decimal(12,2) DEFAULT NULL,
  `actual_quantity` decimal(10,2) NOT NULL,
  `actual_amount` decimal(12,2) DEFAULT NULL,
  `diff_quantity` decimal(10,2) DEFAULT '0.00',
  `diff_amount` decimal(12,2) DEFAULT '0.00',
  `diff_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unit_price` decimal(10,2) DEFAULT NULL,
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`detail_id`),
  KEY `idx_diff_type` (`diff_type`),
  KEY `idx_ingredient_id` (`ingredient_id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_take_id` (`take_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='盘点明细表';