-- Current two-table SHOW CREATE supplied and hash-verified by TL on 2026-09-07.
CREATE TABLE `stock_take` (
  `take_id` bigint NOT NULL AUTO_INCREMENT COMMENT '盘点单ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `take_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '盘点单号',
  `take_date` date NOT NULL COMMENT '日期',
  `take_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'full' COMMENT '类型',
  `category_id` int DEFAULT NULL COMMENT '分类ID',
  `warehouse_id` int DEFAULT NULL COMMENT '仓库ID',
  `total_items` int DEFAULT '0' COMMENT '合计',
  `total_diff_items` int DEFAULT '0' COMMENT '合计',
  `total_diff_amount` decimal(12,2) DEFAULT '0.00' COMMENT '合计',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'draft' COMMENT '状态',
  `operator_id` int DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '操作人',
  `supervisor_id` int DEFAULT NULL COMMENT '监督人ID',
  `supervisor_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `finish_time` datetime DEFAULT NULL COMMENT '时间',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`take_id`),
  UNIQUE KEY `idx_take_no` (`take_no`),
  KEY `idx_status` (`status`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_take_date` (`take_date`),
  KEY `fk_stock_take_operator_id` (`operator_id`),
  KEY `fk_stock_take_supervisor_id` (`supervisor_id`),
  CONSTRAINT `fk_stock_take_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_take_supervisor_id` FOREIGN KEY (`supervisor_id`) REFERENCES `staff_master` (`staff_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='盘点表';

CREATE TABLE `stock_take_detail` (
  `detail_id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `take_id` bigint NOT NULL COMMENT '盘点单ID',
  `store_id` bigint NOT NULL DEFAULT '1' COMMENT '门店ID',
  `line_no` int NOT NULL COMMENT 'line编号',
  `ingredient_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'NULL' COMMENT '食材ID',
  `ingredient_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '原料名称',
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '分类',
  `unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '单位',
  `system_quantity` decimal(10,2) NOT NULL COMMENT '数量',
  `system_amount` decimal(12,2) DEFAULT NULL COMMENT '金额',
  `actual_quantity` decimal(10,2) NOT NULL COMMENT '数量',
  `actual_amount` decimal(12,2) DEFAULT NULL COMMENT '金额',
  `diff_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '数量',
  `diff_amount` decimal(12,2) DEFAULT '0.00' COMMENT '金额',
  `diff_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '类型',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT '单价',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`detail_id`),
  KEY `idx_diff_type` (`diff_type`),
  KEY `idx_ingredient_id` (`ingredient_id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_take_id` (`take_id`),
  KEY `fk_stock_take_detail_ingredient_id` (`ingredient_id`,`store_id`),
  CONSTRAINT `fk_stock_take_detail_ingredient_id` FOREIGN KEY (`ingredient_id`, `store_id`) REFERENCES `ingredient_master` (`ingredient_id`, `store_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_take_detail_take_id` FOREIGN KEY (`take_id`) REFERENCES `stock_take` (`take_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='盘点明细表';
