-- 宴会通知单 v1：执行前请完整备份；脚本可重复执行。
CREATE TABLE IF NOT EXISTS banquet_notice (
  id BIGINT NOT NULL AUTO_INCREMENT,
  notice_no VARCHAR(40) NOT NULL,
  store_id BIGINT NOT NULL,
  booking_id VARCHAR(40) NULL,
  banquet_date DATE NOT NULL,
  banquet_time VARCHAR(20) NULL,
  location VARCHAR(120) NOT NULL,
  reserved_quantity INT NOT NULL,
  banquet_type VARCHAR(60) NOT NULL,
  customer_name VARCHAR(80) NULL,
  customer_phone VARCHAR(30) NULL,
  menu_content LONGTEXT NULL,
  department_items LONGTEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  scan_url VARCHAR(500) NULL,
  scan_name VARCHAR(255) NULL,
  returned_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_banquet_notice_no (notice_no),
  KEY idx_banquet_notice_store_date (store_id, banquet_date),
  KEY idx_banquet_notice_store_status (store_id, status),
  KEY idx_banquet_notice_booking (store_id, booking_id),
  CONSTRAINT chk_banquet_notice_quantity CHECK (reserved_quantity > 0),
  CONSTRAINT chk_banquet_notice_status CHECK (status IN ('draft','published','confirmed','returned','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
