import { createServer } from 'vite'
import vue from '@vitejs/plugin-vue'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'
const require=createRequire(import.meta.url)
const runtime=process.env.YOUJIAN_PLAYWRIGHT_PATH || 'C:/Users/rinom/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'
const { chromium }=require(runtime)
const root=fileURLToPath(new URL('..',import.meta.url))
const output=path.resolve(process.argv[3])
const backend=`http://127.0.0.1:${Number(process.argv[2])}`
const vite=await createServer({root,configFile:false,plugins:[vue()],resolve:{alias:{'@':path.join(root,'src')}},server:{host:'127.0.0.1',port:0,proxy:{'/api':{target:backend,changeOrigin:true}}}})
let browser,page
const failures=[]
try {
  await vite.listen()
  browser=await chromium.launch({channel:'chrome',headless:true})
  page=await browser.newPage({viewport:{width:1440,height:1000},locale:'zh-CN'})
  page.on('pageerror',e=>failures.push(e.message))
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/acceptance/receipt.html`)
  await page.getByTestId('new-receipt').click()
  const dialog=page.getByRole('dialog',{name:'新增入库单'})
  await dialog.locator('.header-fields .el-select').click()
  await page.getByRole('option',{name:'合成验收供应商',exact:true}).click()
  await dialog.locator('.el-table .el-select').click()
  await page.getByRole('option',{name:'浏览器验收原料',exact:true}).click()
  await dialog.locator('.el-input-number input').nth(0).fill('2.50')
  await dialog.locator('.el-input-number input').nth(1).fill('24.00')
  await dialog.getByRole('button',{name:'保存待验收单',exact:true}).focus()
  const createResponse=page.waitForResponse(r=>r.url().endsWith('/api/kitchen-supply/goods-receipts') && r.request().method()==='POST')
  await dialog.getByRole('button',{name:'保存待验收单',exact:true}).click()
  const created=await (await createResponse).json()
  assert.equal(created.code,200)
  assert.equal(Number(created.data.totalAmount),60)
  const id=created.data.receiptId,no=created.data.receiptNo
  let row=page.getByTestId('receipt-list').locator('tr').filter({hasText:no})
  await row.getByRole('button',{name:'验收入库',exact:true}).click()
  const acceptance=page.waitForResponse(r=>r.url().endsWith(`/goods-receipts/${id}/accept`) && r.request().method()==='PUT')
  await page.getByRole('button',{name:'确认入库',exact:true}).click()
  assert.equal((await (await acceptance).json()).code,200)
  await page.reload()
  row=page.getByTestId('receipt-list').locator('tr').filter({hasText:no})
  await row.getByText('已入库',{exact:true}).waitFor()
  await row.getByRole('button',{name:'明细',exact:true}).click()
  const details=page.getByRole('dialog').filter({hasText:'入库明细'})
  await details.getByText('浏览器验收原料',{exact:true}).waitFor()
  await details.getByText('¥60.00',{exact:true}).waitFor()
  assert.deepEqual(failures,[])
  await page.screenshot({path:path.join(output,'receipt-browser-e2e.png'),fullPage:true,animations:'disabled'})
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/acceptance/receipt.html?view=cost`)
  const costRow=page.locator('.cost-table-wrapper tr').filter({hasText:'浏览器成本验收菜'})
  await costRow.getByText('¥6.00',{exact:true}).waitFor()
  await costRow.getByText('30.0%',{exact:true}).waitFor()
  await costRow.getByRole('button',{name:'编辑配方',exact:true}).click()
  const costDialog=page.getByRole('dialog').filter({hasText:'配方编辑'})
  await costDialog.getByText('预计原料成本：¥6.00',{exact:true}).waitFor()
  await page.screenshot({path:path.join(output,'cost-browser-e2e.png'),fullPage:true,animations:'disabled'})
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/acceptance/receipt.html?view=issue`)
  await page.getByRole('button',{name:'新增领料',exact:true}).click()
  const issueDialog=page.getByRole('dialog',{name:'新增领料',exact:true})
  await issueDialog.locator('.el-select').click()
  await page.getByRole('option',{name:'浏览器验收原料',exact:true}).click()
  const issueResponse=page.waitForResponse(r=>r.url().endsWith('/api/kitchen-supply/requisitions') && r.request().method()==='POST')
  await issueDialog.getByRole('button',{name:'提交领料单',exact:true}).click()
  const issued=await (await issueResponse).json()
  assert.equal(issued.code,200)
  let issueRow=page.getByTestId('requisition-list').locator('tr').filter({hasText:issued.data.requisitionNo})
  await issueRow.getByRole('button',{name:'确认出库',exact:true}).click()
  const approved=page.waitForResponse(r=>r.url().endsWith(`/requisitions/${issued.data.requisitionId}/approve`) && r.request().method()==='PUT')
  await page.getByRole('button',{name:'确认领出',exact:true}).click()
  assert.equal((await (await approved).json()).code,200)
  await issueRow.getByRole('button',{name:'登记加工',exact:true}).click()
  const processing=page.getByRole('dialog',{name:'登记加工',exact:true})
  await processing.locator('.el-input-number input').nth(1).fill('0.750')
  await processing.getByRole('button',{name:'保存加工记录',exact:true}).focus()
  const processResponse=page.waitForResponse(r=>r.url().endsWith('/api/kitchen-supply/preprocessing') && r.request().method()==='POST')
  await processing.getByRole('button',{name:'保存加工记录',exact:true}).click()
  const processed=await (await processResponse).json()
  assert.equal(processed.code,200)
  assert.equal(Number(processed.data.yieldRate),75)
  await page.getByTestId('processing-list').getByText('75.00%',{exact:true}).waitFor()
  await page.screenshot({path:path.join(output,'processing-browser-e2e.png'),fullPage:true,animations:'disabled'})
  await page.goto(`http://127.0.0.1:${vite.httpServer.address().port}/acceptance/receipt.html?view=cost`)
  const updatedCost=page.locator('.cost-table-wrapper tr').filter({hasText:'浏览器成本验收菜'})
  await updatedCost.getByText('¥6.40',{exact:true}).waitFor()
  await updatedCost.getByText('32.0%',{exact:true}).waitFor()
  await page.screenshot({path:path.join(output,'cost-after-processing-e2e.png'),fullPage:true,animations:'disabled'})
  assert.deepEqual(failures,[])
  await fs.writeFile(path.join(output,'receipt-browser-result.json'),JSON.stringify({passed:true,receiptId:id,totalAmount:60,requisitionId:issued.data.requisitionId,processingId:processed.data.recordId,yieldRate:75,cost:6.4,salePrice:20,costRate:32,flow:'Vue receipt → requisition → processing → cost page; HTTP → Spring MVC → transaction → MySQL → reload',authentication:'isolated test identity; production authentication not tested'},null,2))
  console.log('RECEIPT_REQUISITION_PROCESSING_COST_BROWSER_FLOW=PASS')
} catch(e) {
  if(page)await page.screenshot({path:path.join(output,'receipt-browser-failure.png'),fullPage:true}).catch(()=>{})
  console.error(e)
  process.exitCode=1
} finally {
  if(browser)await browser.close()
  await vite.close()
}
